sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.3
deploy:
  provider: heroku
  api_key:
    secure: pEjPbJ/Kc+EfeZuZVzu6zigA3BdSq9PkRvTVG0hpyquWfNqDDJrz5m8+pNLGGTOBREejaRrpRI7uJ7C4TBYT4XeENjtC7mlu9gl+UEtkuUMKf2wG44lyX2NtL9n7wgLXdMQowrhZuseFjE1CoJwowXJOYaxbCVYoKPQilZwiZhOixHRVJKMJMm2caGeu/Var+US0xDUMmCfDKMHtNZCD1pRdD2Hk4IUAgOdGsmKd0Rmzlv1AI6HYiz8Ez5SJwByo/lUZmLlOOUzmR+loLPKtPRdk9vysGsU8W5YFNej2kL8XKydrSklYmcgdqLSrehKesumwrLk9UQV3PmVkmrHMxVmEIOWcXXSaCEnsNh99dpqeqJovPIQk5/41RK+oehuZnuo/inS33TOZM68rA+WP0WAGM9q7SuhUAiFLNcx64ilTEqq7YUVYhY/1j43xhv2sqe74nMLH2onX2M2m39v47IqsxCJwCw7T8Pb1y4o2fT2Xl1HGxVxUXXjaFuzHOw8rPGqZI0Z7xHDuknkX2PLz+J14L1GV42OQzpB5VWBX3YSpHCcGnlBp8gJckci6DafCN58rlVpw1nRcg9FBIPmNjDY6fxMsWow0p407Ukf2FsjaAe3WLDoXrYIY6n/X8qVoRzDT/fUXfry7Oi5zH9iNifNAoqWh0LgQNp6F0gB09r0=
  app: webringclub
  on:
    repo: emillon/webring.club
    branch: master
before_install:
  - gem update --system
  - gem install bundler
